
export const BloodElfMaleFirstNamePartsTwo = [
    ["A","Ael","Aen","Al","Ala","Alam","Alen","Ales","Alsu","Amor","An","Ar","As","Asta","Astal","Ba","Be","Bel","Bem","Bema","Bemar","Bith'","Cai","Caida","Cam","Cel","Celo","Celoe","Co","Col","Dar","Dar'","Dare","El","Elro","En","Eri","Fa","Fano","Far","Fel","Fele","Ge","Gel","Gelan","Geran","Ha","Hal","Hat","He","Hel","Her","Ido","Idon","Ine","Ineth","Ith","Ith'","Ithe","Ithi","Ithil","Je","Jen'","Ka","Kae","Kaen","Kan'","Kar","Kath'","Ke","Kee","Keel","Kel","Kele","Keya","Krae","Kre","Kren'","Krenn'","La","Lan","Landra","Laren","Le","Lelo","Leo","Leth","Leth'","Lo","Lon","Ma","Matha","Mela","Mele","Meli","Mir","Ne","Ner","Neri","No","Norae","Oni","Osse","Pa","Pae","Pan","Par","Per","Pera","Pona","Qual","Que","Quel","Ra","Ral","Sa","Sal","Sel","Sen","Sin","So","Sol","Syl","Tal","Tan","Te","Ter","To","Ty","Tyn","Tynia","Tyniar","Tyr","Vae","Val","Van","Var","Velen","Vor'","Vra","Vy","Vyn","Win","Wyl","Ya","Za","Zan","Ze","Zela"],
    ["dan","danis","den","deyn","dis","don","dor","doran","dril","dris","lan","lanis","larin","laris","lastor","lath","lemar","len","leron","lerun","lestis","lien","lin","linan","lion","lios","lis","lon","lor","mar","marrin","min","mir","nan","nar","nas","nath","nesh","nian","niar","nien","nin","nir","nis","nomir","nus","rad","ral","ran","ranir","ranis","rel","ren","renis","rian","ric","riel","ril","rin","ris","rodan","ron","run","sel","sen","sil","stus","talor","than","thar","thas","thein","thelon","then","thenis","theol","theon","theril","thin","this","thol","thos","tis","tor","tus","valin","vedon","velion"],
];

export const BloodElfMaleFirstNamePartsOne = [
    ["Aer","Al","Bac","Baem","Bem","Bit","Caem","Cam","Duy","Er","Hat","Her","In","Inet","It","Jen","Keel","Lor","Mat","Mel","Nor","Par","Per","Rah","Saet","Sat","Tan","Wel","Win","Yat","Zan","Zel","Pe","Qu","Qui","Ra","Sa","Sae","So","Ta","Vy","Vya","We","Wele","Wi","Ya","Za","Zae","Ze","No","Matha","Ma","Kre","Kee","He","Eri","Bema","Baema","Bae","Ala","Aeri","Ba","Be","Bi","Ca","Cae","Dra","Drae","Du","Ha","Ine","Je","Lo","Me","Norae","Oni","Pa"],
    ["aen","aesh","aeth","ald","an","anis","aris","arrin","as","ash","ath","en","ean","eath","eon","eron","esh","iel","il","ilan","illan","in","ir","is","ith","us","azen","azhen","uzen","'thema","'themar","'theas","'danas","'daras","'thul","'thas","'thaes","beron","den","dis","dron","haen","hean","hein","hen","hin","laen","lath","laeth","len","leron","ma","mae","na","nis","ren","rim","rin","ris","ron","rus","saen","sen","thaen","than","ven","veth","vaen","ten","nae","neas","theas","lae","laen","zaen","zen"],
];

export const BloodElfFemaleFirstNamePartsOne = [
    ["A","Ael","Aelna","Ala","Alam","Alei","Ami","An","Ara","Au","Auri","Auro","Be","Bel","Bele","Belo","Bema","Bemar","Cai","Ce","Cee","Cel","Da","Dab","Dae","Dar","De","Dela","Dena","Dey","E","El","Ela","Eli","Ely","Eme","Era","Ere","Eri","Ero","Fa","Fara","Fey","Fi","Ga","Gala","Gar","Garri","Glo","Ha","Han","Ir","Ja","Jae","Ji","Ka","Kali","Kalin","Kan","Kana","Kee","Kel","Keli","Ki","Kina","Ky","La","Lan","Lari","Laria","Li","Lo","Lor","Lora","Loral","Ly","Lyna","Ma","Mar","Me","Mel","Mir","Na","Nar","Nari","Ni","No","O","Oli","Ra","Rae","Sa","Sal","Sari","Se","Seda","Sha","Shar","She","Sher","Si","Sila","Silan","Sy","Syl","Ta","Tan","Ter","Terel","Ty","Tyn","Va","Val","Ve","Vela","Velan","Za","Zae","Zal","Zan","Zar","Zara","Zaral","Zya","Zyan"],
    ["da","dana","del","den","dina","dine","dori","dra","ferous","la","lan","lana","lania","lanne","latha","laya","le","lene","lenn","lestra","li","lia","lina","linda","line","lis","lonis","ma","mine","misa","na","nara","naria","ne","neda","nel","ni","nia","nice","niel","nis","nise","nore","ra","raden","re","rea","ri","ria","rianna","ridel","rin","rina","rion","rise","rous","sa","salia","sara","sendra","sia","silla","stra","tasia","thalis","thel","thos","via","zara","zia"],
];

export const BloodElfFemaleFirstNamePartsTwo = [
    ["Ael","Al","Am","Amo","Amor","An","Az","Bel","Cel","Daen","Dan","Dar","Der","El","Em","Il","Kal","Keal","Kel","Lyn","Nar","Nat","Sed","Syl","Tal","Tan","Tel","Tyn","Vel","Zan","Zar","Zat","Ol","Ela","Ele","Dey","Aela","Aele","Ala","Ale","Aza","Azae","Bele","Ca","Cae","Cai","Cay","Ce","Cea","Cee","Da","Dae","Day","De","Fae","Fe","Fey","Ile","Jo","Jovi","Ka","Ke","Kee","Ky","Lae","Lea","Li","Lia","Ly","Na","No","Novi","Oli","Se","Sha","Sy","Sye","Ta","Tali","Te","Teli","Ty","Tye","Ve","Vela","Za","Zae","Ze","Zea","Zy","Zya"],
    ["aena","alda","alle","ana","anae","andra","anea","ann","anna","anne","anni","ara","eda","elda","eli","elly","enna","era","erae","erea","estra","iah","ice","inda","ine","inne","inth","ise","onia","ori","yn","yna","ynna","da","dine","dori","dra","drae","drea","drel","drin","drine","le","lean","leane","len","lenn","lenne","li","lia","ly","na","nia","nice","ra","rae","rea","rel","riah","rin","rine","rise","vea","via","vie","wae","we","wea"],
];

export const BloodElfLastNameParts = [
    ["ancient","arcane","autumn","azure","black","blood","bold","brass","bright","bronze","cinder","cold","crimson","dark","dawn","day","dew","down","dread","dual","dusk","eager","ember","even","evening","ever","fire","flame","flare","free","glare","glow","gold","golden","grand","great","grim","heart","high","hot","keen","leaf","lean","light","livid","long","mage","mirth","moon","morning","morrow","night","nimble","odd","pale","peace","phoenix","radiant","rich","right","rose","rune","sharp","silent","silver","slim","solar","somber","soul","spark","star","strong","summer","sun","sweet","swift","tinder","true","twin","velvet","violet","warm","white","wild","wind"],
    ["band","bane","beam","bell","binder","birth","blade","blood","blossom","breath","bringer","brook","burn","burst","cloud","crown","depth","desire","down","dream","dreamer","faith","fall","fate","feast","feather","field","flame","flare","flight","flow","fluke","fold","force","forge","fury","gaze","gazer","gift","gleam","guard","heart","hide","hold","hope","kind","light","love","luck","might","mind","mourn","path","poem","post","power","pride","range","ray","reaver","rest","seeker","sense","shade","shadow","shard","shield","shine","sign","singer","sky","smile","song","sorrow","spark","spear","spell","spirit","sprinter","stalker","star","strider","sun","switch","sworn","thread","trail","trick","truth","twist","vale","veil","vein","walker","whisper","wing","wish","wood"],
];
