
export const NightElfeMaleFirstNamePartsOne = [
    ["A","A'","Aly","Ay","Cy","Ca","E","E'","Ely","Ey","Fa","Fy","Ga","Ha","He","Hy","I","Ily","Iy","Ji","Ja","Ka","Ke","Ky","La","Le","Ly","Ma","Me","My","Na","Ne","Ny","Re","Ra","Ry","Sa","Sha","She","Sy","Tha","The","Thy","U","Uy","Wa","We","Y","Y'","Ya","Ye","Al","All","An","Am","As","Ar","El","Em","En","Er","Es","F","Fil","Fel","Fyl","Gal","Il","Ill","K","L","Lil","Lyl","Lel","M","Myt","Myth","Mor","Math","Mil","Myl","Mel","N","Nyl","Nil","Nel","Nyt","Nyth","S","Sil","Syl","Sel","Sh","Shyl","Th","Thel","Thyl","Thil","W","Yl","Yll"],
    ["adaen","adaern","adan","adarn","adean","adearn","adon","adros","aedan","aedarn","aedon","aeith","aelar","aelas","aelath","aeleas","aeleath","aellas","aellath","aelleas","aelleath","aellor","aellorn","aelor","aelorn","aenal","aenas","aenel","aenul","aerian","agorn","alaeas","alaeath","alaes","alaeth","alas","alath","aleas","aleath","alias","aliath","allaes","allaeth","allas","allath","alleas","alleath","anaes","anai","anas","andiir","anelle","annul","arion","aste","eadon","eaith","ealaes","ealaeth","ealar","eallaes","eallaeth","eanal","eanel","edon","egorn","elar","elir","ellor","ellorn","elor","elorn","engyl","erian","erias","eth","ethil","idan","ilaeth","ileath","illaeth","illeath","odraen","odren","oraen","orean","oren","umon","'dir","'las","dan","dent","diir","dlaess","dlas","dlass","dleass","dos","draen","draes","draeth","dral","dran","dras","dreas","dreath","dren","driel","dries","drieth","dris","dron","drus","dryn","gorm","gorn","gos","gyael","gyal","gyl","laen","laess","laeth","lass","ldor","lean","leass","leath","lian","llaen","llean","llian","n'ra","naeth","nas","nath","neath","nrus","nul","rae","raei","raes","raeth","rai","rand","rea","reas","reath","ries","rieth","rin","rion","ris","saem","sam","seam","shar","thae","thaes","tharion","thas","theas","thiel","wen"]
];

export const NightElfeMaleFirstNamePartsTwo = [
    ["A","Al","Ala","Ale","Alen","An","Anta","Ar","Ba","Bal","Bari","Ben","Bha","Bhal","Bol","Bran","Ca","Ce","Cere","Cerel","Cha","Cy","Da","Dal","Dan","De","Den","Dena","Do","Dra","Drae","E","El","Ele","Elen","En","Ere","Eve","Fa","Fah","Fal","Fan","Fara","Fel","Fo","Fy","Fyl","Ga","Gae","Gar","Ger","Gron","Ha","Hal","I","Il","Ira","Ka","Ke","Kel","Ker","Kha","Khar","La","Lar","Ma","Mal","Malu","Man","Mana","Mar","Mavo","Mela","Meli","My","Mydra","Na","Nan","O","Oren","Pel","Ra","Rae","Re","Rel","Sa","Sae","Se","Sel","Sha","Si","Sil","Sura","Ta","Tal","Tala","Te","Tela","Teren","Tero","Tu","Ul","Val","Volo","Yl","Yli","Za"],
    ["daan","daar","dal","damyr","dan","dant","daran","daron","das","del","diir","dil","dilad","diss","dolar","don","dor","doril","dos","dral","drannul","dreas","dris","drol","dron","dryn","fran","gorn","halan","laar","lad","ladan","laine","lais","lan","lar","las","lean","lian","lidan","lin","lomon","lonian","lor","lorn","lorne","minon","mon","naal","nados","nar","nas","ndaar","nel","nelor","neth","nian","nis","nol","non","norion","nul","ran","randiir","rannul","ras","ren","rendil","rengyl","renthil","ressian","rian","riel","ril","rin","rion","ris","rith","rius","rol","rolas","ron","ros","rus","ryeth","sin","stren","tas","thaan","thannius","tharion","thas","thidan","thil","thir","this","thras","turas","vine","voris"]
];

export const NightElfeFemaleFirstNamePartsOne = [
    ["A","A'","Aly","Ay","Cy","Ca","E","E'","Ely","Ey","F","Fa","Fy","Ga","Ha","He","Hy","I","Ily","Iy","Ji","Ja","Ka","Ke","Ky","La","Le","Ly","Ma","Me","My","Na","Ne","Ny","Sa","Sha","She","Sy","Tha","The","Thy","U","Uy","Wa","We","Y'","Ya","Ye","S","Sil","Syl","Sel","Sh","Shyl","Th","Thel","Thyl","Thil","W","Y","Yl","Yll","Al","All","An","Am","As","Ar","El","Em","En","Er","Es","Fil","Fel","Fyl","Gal","Il","Ill","K","L","Lil","Lyl","Lel","M","Myt","Myth","Mil","Myl","Mel","N","Nyl","Nil","Nel","Nyt","Nyth"],
    ["adya","adyia","aedya","aeith","aelas","aeleas","aellas","aelleas","aena","aenas","aenea","aenia","aenna","aenya","aercia","aesa","aesia","alaea","alaeas","alaes","alaria","alas","aleas","aleath","alia","alias","allaes","allas","alleas","anaes","anai","anaria","anas","anea","anelle","ania","anna","aria","arii","asae","asea","asia","aste","eaith","ealaes","eallaes","eana","eanna","earcia","easa","easia","ene","enia","enna","enya","ercia","eria","erias","ethil","ethis","ilaeth","ileath","illaeth","illeath","ina","indae","indea","india","inne","is'ta","iyell","ora","yell","yna","ynna","ysa","ysae","ysea","yssa","yssae","yssea","yssia","ythis","yura","yurae","yurea","'lyn","'lynn","cina","draeth","dreath","driel","drieth","dris","hara","lae","laea","laei","laeth","lea","leae","leath","lia","liene","lora","lysae","lysea","lyssa","lyssae","n'ra","nas","nya","nyae","nysa","nysae","nysea","nyssa","nyssae","nyssea","rae","raei","raeth","rai","rea","reath","rieth","riia","rnae","rnea","thae","thea","wen"]
];

export const NightElfeFemaleFirstNamePartsTwo = [
    ["A","Aa","Aay","Ae","Aeo","Aetha","Ai","Aine","Al","Ala","Alai","Alan","Ali","Aly","Ama","Ana","Ari","Aria","Ary","Arye","Asta","Ava","Aya","Be","Beca","Bie","Bya","Ca","Cary","Cay","Ce","Da","Dae","Dal","Dan","De","Del","Dela","Den","Dira","Dori","Dul","Ea","Ela","Elan","Ele","Elen","Eli","Ella","Ellae","Ellan","Ellen","Ely","Elyn","Eri","Fae","Faely","Fyre","Gra","I","Idri","Idria","Il","Illi","Illia","Ilye","Ir","Ire","Ja","Jae","Jaea","Jael","Jay","Jer","Ke","Kei","Key","Kin","Ky","Kyla","Kyn","La","Lan","Le","Lela","Len","Li","Lila","Lla","Ly","Ma","Mae","Mali","Mar","Me","Mel","Mere","Merel","Mi","Mor","Mori","My","Nhe","Ny","Nyri","Rae","Re","Rel","Rela","Rhy","Rhya","Ry","Rya","Sa","Sae","San","Se","Sel","Sela","Seri","Seria","Shal","Si","Sil","Silda","Sin","So","Sy","Syl","Te","Tel","Tes","Tha","The","Tri","Tria","Ul","Ve","Vel","Ves","Vi","Vina","Vis","Vivi","Vivia","Yae"],
    ["canna","ciea","da","danair","dia","dira","dri","dria","drieth","drina","dris","dyia","la","lah","lais","lanai","lanea","lania","lanna","lara","larin","las","lea","lenai","lene","lia","lienne","lin","lina","liynn","lya","lyia","lylah","lynn","lynna","lysia","lyssa","ma","mai","mara","moora","na","nai","nar","nasha","naya","ne","nea","nia","nira","nysil","ra","rai","ralyn","ran","rania","re","rela","rena","renna","ri","ria","riala","riale","riana","rianna","rias","rien","rii","riia","rin","rinar","risse","rya","ryn","rynn","ryssia","sa","sana","se","sera","sha","shia","sia","sina","stra","taria","tarii","tarre","teran","thea","thil","tia","vana","vanna","varia","ya","yana","yell","yenda"]
]

export const NightElfeLastNameParts = [
    ["Amber","Autumn","Bear","Black","Blade","Blue","Dark","Dawn","Dew","Dusk","Even","Far","Feather","Fog","Forest","Green","Leaf","Light","Luna","Mist","Moon","Moss","Night","Ocean","Rain","Rapid","Raven","Sage","Sea","Shade","Shadow","Shield","Silent","Silver","Sky","Spirit","Stag","Star","Still","Stone","Storm","Strong","Summer","Sun","Swift","Thunder","Tree","True","Void","Wild","Wind","Winter","Wood"],
    ["arrow","blade","bloom","blower","bough","bow","branch","breath","breeze","caller","cloud","clouds","crest","dancer","dew","eye","feather","fire","flower","forest","gazer","grove","heart","helm","lance","leaf","light","mane","might","moon","oak","rage","runner","scribe","seeker","shade","shadow","shot","singer","sky","snow","song","spear","spirit","spyre","stalker","star","strike","striker","swift","sword","thorn","tree","walker","watcher","water","weaver","whisper","wind","wing"]
];
