
export const RACES_AGES = {
    // DWARFS
    LIMIT_CHILDHOOD_AGE_DWARF: 14,
    LIMIT_TEENAGEHOOD_AGE_DWARF: 24,
    LIMIT_ADULTHOOD_AGE_DWARF: 60,
    LIMIT_SENIORHOOD_AGE_DWARF: 120,

    // DRAENEIS
    LIMIT_CHILDHOOD_AGE_DRAENEI: 14,
    LIMIT_TEENAGEHOOD_AGE_DRAENEI: 24,
    LIMIT_ADULTHOOD_AGE_DRAENEI: 200,
    LIMIT_SENIORHOOD_AGE_DRAENEI: 500,
}
