export const CHARACTER_ATTRIBUTES_CONFIG = {
    STRENGTH_MIN: 0,
    STRENGTH_MAX: 100,

    DEXTERITY_MIN: 0,
    DEXTERITY_MAX: 100,

    CONSTITUTION_MIN: 0,
    CONSTITUTION_MAX: 100,

    INTELLIGENCE_MIN: 0,
    INTELLIGENCE_MAX: 100,

    CHARISMA_MIN: 0,
    CHARISMA_MAX: 100,

    WISDOM_MIN: 0,
    WISDOM_MAX: 100,

    LUCK_MIN: 0,
    LUCK_MAX: 100,

    PERCEPTION_MIN: 0,
    PERCEPTION_MAX: 100,

    WILLPOWER_MIN: 0,
    WILLPOWER_MAX: 100,
}
