import { RACES_AGES } from "Config/Ages"
import { AgeOfRace } from "Resources/Models/Game/AgeOfRace"

export const AgeOfDraenei = new AgeOfRace(
    RACES_AGES.LIMIT_CHILDHOOD_AGE_DRAENEI,
    RACES_AGES.LIMIT_TEENAGEHOOD_AGE_DRAENEI,
    RACES_AGES.LIMIT_ADULTHOOD_AGE_DRAENEI,
    RACES_AGES.LIMIT_SENIORHOOD_AGE_DRAENEI
)


export const AgeOfDwarf = new AgeOfRace(
    RACES_AGES.LIMIT_CHILDHOOD_AGE_DWARF,
    RACES_AGES.LIMIT_TEENAGEHOOD_AGE_DWARF,
    RACES_AGES.LIMIT_ADULTHOOD_AGE_DWARF,
    RACES_AGES.LIMIT_SENIORHOOD_AGE_DWARF
)
